### ISSUE TITLE
Dstat I/O monitoring is incorrect

### ISSUE THREAD

**Issue by FelixNeutatz** [peelframework/peel#106]
During the last week I monitored our peel bundle(https://github.com/fschueler/sysml-benchmark) using dstat (with the default configuration). It turned out that the file dstat is reading from has incorrect data statistics: /proc/diskstats
The way how I figured that out was that I queried the I/O statistics per process using:  /proc/[processid]/io 

So I queried the process id of the corresponding systems and got for example number of read bytes per process by this script:

```
#SPARK 
OUTPUT_SPARK="$(ps -ef | grep "org.apache.spark.deploy.worker.Worker" | grep -v grep | awk '{print $2}')"
READ_SPARK="$(cat /proc/"${OUTPUT_SPARK}"/io | grep "rchar:" | awk '{print $2}')"

#Flink
OUTPUT_HADOOP="$(ps -ef | grep "/share/hadoop/peel/systems/hadoop-2.7.1/logs -Dhadoop.log.file=hadoop-hadoop-datanode" | grep -v grep | awk '{print $2}')"
READ_HADOOP="$(cat /proc/"${OUTPUT_HADOOP}"/io | grep "rchar:" | awk '{print $2}')"

#Hadoop
OUTPUT_HADOOP="$(ps -ef | grep "/share/hadoop/peel/systems/hadoop-2.7.1/logs -Dhadoop.log.file=hadoop-hadoop-datanode" | grep -v grep | awk '{print $2}')"
READ_HADOOP="$(cat /proc/"${OUTPUT_HADOOP}"/io | grep "rchar:" | awk '{print $2}')"
```

I compared the number of bytes read reported by  /proc/diskstats to /proc/[processid]/io. The result is that  /proc/diskstats is reporting way less than /proc/[processid]/io (7053312 bytes << 31215239924 bytes). I run all my experiments on the IBM-Power-1 cluster.

Any ideas how to tackle this problem?

Felix

**Comment by aalexandrov** [comment]
@FelixNeutatz any news on the issue?

**Comment by FelixNeutatz** [comment]
no, nothing new.

**Comment by FelixNeutatz** [comment]
I forwarded the question to the Dstat people: [Dstat repo](https://github.com/dagwieers/dstat/issues/126)

**Comment by FelixNeutatz** [comment]
For now, I found a workaround using the following Dstat config: [dstat-0.7.2.conf](https://github.com/fschueler/sysml-benchmark/blob/master/sysml-benchmark-bundle/src/main/resources/config/dstat-0.7.2.conf)

Not sure, whether this is a solution in general

**Comment by FelixNeutatz** [comment]
It turns out that caching is the problem. To get the "real" numbers one can "overwrite" the cache by running a different pundle e.g. https://github.com/FelixNeutatz/DstatCheck which produces a 100GB dataset and reads it.
