### ISSUE TITLE
dstat download path doesn't exist anymore

### ISSUE THREAD

**Issue by carabolic** [peelframework/peel#112]
Peel tries to download `dstat-0.7.2` from https://fossies.org/linux/privat/dstat-0.7.2.tar.gz. But it seems that the file doesn't exist anymore. Maybe we should update to `dstat-0.7.3` which does exist.

To reproduce the bug, delete/move the dstat archive from the peel downloads directory and delete/move the dstat system from the peel system directory.

**Comment by carabolic** [comment]
Upon some investigation I found the official place to download at https://github.com/dagwieers/dstat/archive/0.7.2.tar.gz. But this one has a different md5 as the one specified in the `reference.dstat-0.7.2.conf`. Should I replace them anyway?

**Comment by aalexandrov** [comment]
Yes, and maybe also add 0.7.3 as version (needs an entry in extensions.scala and an additional `*.conf` file.

**Comment by aalexandrov** [comment]
Fixed in v1.1.6 with e9b884ab32c03a4196bde0daf8cc25eb0d46be2a.
