### ISSUE TITLE
Flink's DistributedLogCollection ignores JobManager Logs

### ISSUE THREAD

**Issue by verbit** [peelframework/peel#85]
The Flink's DistributedLogCollection does not copy the JobManager logs into the results folder.

The problem is that the current RegExp (see linked code lines) iterates only over all slaves. However, the JobManager logs are suffixed with the master hostname.

https://github.com/peelframework/peel/blob/master/peel-extensions/src/main/scala/org/peelframework/flink/beans/system/Flink.scala#L61-L62

**Comment by aalexandrov** [comment]
@verbit thanks for reporting this, I now see that we have similar issues with HDFS as well.

Can you verify whether this patch resolves the problem? I can then push a fix.

```scala
  override def slaves = config.getStringList(s"system.$configKey.config.slaves").asScala
  override def master = config.getString(s"system.$configKey.config.yaml.jobmanager.rpc.address")

  /** The patterns of the log files to watch. */
  override protected def logFilePatterns(): Seq[Regex] = {
    val user = Pattern.quote(config.getString(s"system.$configKey.user"))
    Seq(
      s"flink-$user-jobmanager-\\d+-$master\\.log".r,
      s"flink-$user-jobmanager-\\d+-$master\\.log".r) ++
    slaves.map(Pattern.quote).flatMap(slave => Seq(
      s"flink-$user-taskmanager-\\d+-$slave\\.log".r,
      s"flink-$user-taskmanager-\\d+-$slave\\.out".r))
  }
```

**Comment by verbit** [comment]
Yes, looks good to me.
