### ISSUE TITLE
ExperimentSequence with multiple parameters

### ISSUE THREAD

**Issue by akunft** [peelframework/peel#86]
`ExperimentSequence` already has the facilities to create crossed and zipped parameters, but the according ctors are missing.

Lets create them :)

I have a prototype for the crossed variant [here](https://github.com/akunft/peel/blob/multiple-parameters/peel-core/src/main/scala/org/peelframework/core/beans/experiment/ExperimentSequence.scala)

which lets you define the crossed parameters like this:

```xml
                <constructor-arg name="crossParam">
                    <list>
                        <bean class="org.peelframework.core.beans.experiment.ExperimentSequence.Parameter">
                            <constructor-arg name="name" value="topXXX" />
                            <constructor-arg name="vals">
                                <list>
                                    <value>top005</value>
                                    <value>top010</value>
                                    <value>top020</value>
                                </list>
                            </constructor-arg>
                        </bean>
                        <bean class="org.peelframework.core.beans.experiment.ExperimentSequence.Parameter">
                            <constructor-arg name="name" value="scale" />
                            <constructor-arg name="vals">
                                <list>
                                    <value>10000</value>
                                    <value>20000</value>
                                    <value>30000</value>
                                </list>
                            </constructor-arg>
                        </bean>
                    </list>
                </constructor-arg>
```

I suggest a third ctor parameter `type` to enable the user to choose between `crossed` and `zipped`.

**Comment by aalexandrov** [comment]
The indended use is to use the `parameters: ExperimentSequence.Parameters` parameter in the corresponding constructors and pass an explicilty created `Parameters` instance (e.g. `ZippedParameters` or `CrossParameters`).

This works for XML, but is a bit verbose and hard to understand.

For zipped and crossed parameters, Scala-based config seems to be a much better fit, as you can just have a 

```scala
new ExperimentSequence(for {
  p1 <- Seq('1', '2', '3')
  p2 <- Seq('a', 'b', 'c')
} yield experiment(p1, p2))

**Comment by akunft** [comment]
Yes, I see. My bad, then this works all fine :)
