### ISSUE TITLE
Add --loglevel option

### ISSUE THREAD

**Issue by robert-schmidtke** [peelframework/peel#88]
It'd be really cool if it was possible to specify the log level when running `peel.sh`, this would make it easier to develop and test extensions. I'm adding XtreemFS as a `System` to Peel and I'd like to add some `logger.debug(...)` statements during `start()` and `stop()`.

**Comment by aalexandrov** [comment]
Great idea, the implementation should be straight forward:

- [ ] Add an extra `--loglevel` option [here](https://github.com/TU-Berlin-DIMA/BDAPRO.SS16/issues/7#issuecomment-222442475) with an enumerated tomain (`DEBUG`, `INFO`) and a default value `INFO`.
- [] Propagate the Argparse4J namespace value of `app.log.level` to a same-named System property [here](https://github.com/peelframework/peel/blob/master/peel-core/src/main/scala/org/peelframework/core/cli/Peel.scala#L61).
- [ ] Adapt the log level based on the `app.log.level` value [here](https://github.com/peelframework/peel/blob/master/peel-core/src/main/scala/org/peelframework/core/cli/Peel.scala#L77).

**Comment by aalexandrov** [comment]
This will be included in `1.0.0-rc6`.
