### ISSUE TITLE
java.lang.NoSuchFieldError: tupleType

### ISSUE THREAD

**Issue by noproblem666** [peelframework/peel#91]
When trying to run the peel-wordcount experiment on our cluster we get the following exception message in the "run.err" file:

> java.lang.NoSuchFieldError: tupleType
>         at org.peelframework.wordcount.flink.FlinkWC$$anon$2.protected$tupleType(FlinkWC.scala:20)
>         at org.peelframework.wordcount.flink.FlinkWC$$anon$2$$anon$1.<init>(FlinkWC.scala:20)
>         at org.peelframework.wordcount.flink.FlinkWC$$anon$2.createSerializer(FlinkWC.scala:20)
>         at org.apache.flink.optimizer.postpass.JavaApiPostPass.createSerializer(JavaApiPostPass.java:283)
>         at org.apache.flink.optimizer.postpass.JavaApiPostPass.traverseChannel(JavaApiPostPass.java:252)
>         at org.apache.flink.optimizer.postpass.JavaApiPostPass.traverse(JavaApiPostPass.java:97)
>         at org.apache.flink.optimizer.postpass.JavaApiPostPass.postPass(JavaApiPostPass.java:81)
>         at org.apache.flink.optimizer.Optimizer.compile(Optimizer.java:518)
>         at org.apache.flink.optimizer.Optimizer.compile(Optimizer.java:397)
>         at org.apache.flink.client.program.Client.getOptimizedPlan(Client.java:233)
>         at org.apache.flink.client.program.Client.getOptimizedPlan(Client.java:521)
>         at org.apache.flink.client.program.Client.runBlocking(Client.java:314)
>         at org.apache.flink.client.program.ContextEnvironment.execute(ContextEnvironment.java:70)
>         at org.apache.flink.api.scala.ExecutionEnvironment.execute(ExecutionEnvironment.scala:627)
>         at org.peelframework.wordcount.flink.FlinkWC$.main(FlinkWC.scala:25)
>         at org.peelframework.wordcount.flink.FlinkWC.main(FlinkWC.scala)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:497)
>         at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:395)
>         at org.apache.flink.client.program.Client.runBlocking(Client.java:252)
>         at org.apache.flink.client.CliFrontend.executeProgramBlocking(CliFrontend.java:676)
>         at org.apache.flink.client.CliFrontend.run(CliFrontend.java:326)
>         at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:978)
>         at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1028)
> 
> The exception above occurred while trying to run your command.
 
The console log shows the following: https://gist.github.com/noproblem666/506c8d296aa85a05ea4f81148c38deb8

What is the cause of this problem and how can we fix it? 

Thanks and Best regards,
Robert

**Comment by aalexandrov** [comment]
Seems to be a linkage error in the `peel-wordcount` app against Flink.

Which path from the manual are you following (Pre-Packaged Binary or Maven Archetype)?

**Comment by noproblem666** [comment]
We cloned the `peel` and `peel-wordcount` repositories and built it ourself with `mvn clean install` instead of using archetype or pre-packaged binary.

**Comment by aalexandrov** [comment]
OK, I suggest to make sure that you adapt your `peel-wordcount` sources upgrade to `flink-1.0.3`.

**Comment by aalexandrov** [comment]
This should be resolves with the latest version of the master.

**Comment by noproblem666** [comment]
I pulled the latest version of the `peel` repository and tried to built it with `mvn clean install`.
Unfortunately I get the following error message: 
```

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] peel .............................................. FAILURE [26.436s]
[INFO] peel-archetypes ................................... SKIPPED
[INFO] peel-flinkspark-bundle ............................ SKIPPED
[INFO] peel-flink-bundle ................................. SKIPPED
[INFO] peel-spark-bundle ................................. SKIPPED
[INFO] peel-core ......................................... SKIPPED
[INFO] peel-extensions ................................... SKIPPED
[INFO] peel-empty-bundle ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.879s
[INFO] Finished at: Thu Jun 09 13:21:16 CEST 2016
[INFO] Final Memory: 18M/366M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jasig.maven:maven-notice-plugin:1.0.4:check (check-notice) on
project peel-parent: Execution check-notice of goal org.jasig.maven:maven-notice-plugin:1.0.4:check
failed. NullPointerException -> [Help 1]
```

**Comment by aalexandrov** [comment]
This was an error with the `license:check` goal, should be resolved with the latest master. If not you, can just disable the plugin from the main pom.xml.

**Comment by noproblem666** [comment]
Works fine, thanks!

**Comment by aalexandrov** [comment]
No problem.
